# Generated by Django 5.0.1 on 2024-03-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.CharField(blank=True, default=400, max_length=700, null=True),
        ),
    ]
