# Generated by Django 5.1.2 on 2024-10-26 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=400, max_digits=10, null=True),
        ),
    ]
